= Data types

== Integral type 
*python provides two built in integral types.*

* int and bool
* Both integers and Booleans are immutable.
* When used in Boolean expressions, 0 and False are False, and any other integer and True are True.
* When used in numerical expressions True evaluates to 1 and False to 0.
* to use the integers in other number bases for example :
----
>>> 0xDECADE
14600926
>>> 0b01010101
85
>>> 0o676
446
>>>
----
* When rounding is used on a floating point number and integer the result is subtle. But when negative rounding is done then there is a different kind of rounding achieved.
----
>>> round(66.0011,2)
66.0
>>> round(12, 4)
12
>>> round(66.0011, -2)
100.0
>>> round(66.0011, -1)
70.0
>>> round(66.0011, -3)
0.0
>>> round(66.0011, -4)
0.0
>>> round(66, -4)
0
>>> round(66, -1)
70
>>> round(66, -2)
100
>>> round(66, -3)
0
>>>
----

== Boolean type
* There are two built-in Boolean objects: True and False
----
>>> t = True
>>> t
True
>>> t and False
False
>>>
----
* Python provides three logical operators: and, or, and not. Both and and or use short-circuit logic and return the operand that determined the result, whereas not always returns either True or False.
----
>>> not t
False
>>> f = False
>>> not f
True
----

== Floating point datatype
* Python provides three kinds of floating-point values: the built-in float and complex types, and the decimal.
* All three are immutable.
* Numbers of type float are written with a decimal point, or using exponential notation, for example, 0.0, 4., 5.7, -2.5, -2e9, 8.9e-4.

== Complex numbers

* The complex data type is an immutable type that holds a pair of floats, one representing the real part and the other the imaginary part of a complex number.
* Literal complex numbers are written with the real and imaginary parts joined by a + or - sign, and with the imaginary part followed by a j.* Here are some examples: 3.5+2j, 0.5j, 4+0j, -1-3.7j. Notice that if the real part is 0, we can omit it entirely.
